/* tslint:disable */
/* eslint-disable */
/**
 * PalWorld OpenAPI
 * PalWorld OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfoResponse
 */
export interface InfoResponse {
    /**
     * 
     * @type {string}
     * @memberof InfoResponse
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof InfoResponse
     */
    servername: string;
    /**
     * 
     * @type {string}
     * @memberof InfoResponse
     */
    description: string;
}

/**
 * Check if a given object implements the InfoResponse interface.
 */
export function instanceOfInfoResponse(value: object): boolean {
    if (!('version' in value)) return false;
    if (!('servername' in value)) return false;
    if (!('description' in value)) return false;
    return true;
}

export function InfoResponseFromJSON(json: any): InfoResponse {
    return InfoResponseFromJSONTyped(json, false);
}

export function InfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'servername': json['servername'],
        'description': json['description'],
    };
}

export function InfoResponseToJSON(value?: InfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'servername': value['servername'],
        'description': value['description'],
    };
}

