/* tslint:disable */
/* eslint-disable */
/**
 * PalWorld OpenAPI
 * PalWorld OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnounceRequest
 */
export interface AnnounceRequest {
    /**
     * 
     * @type {string}
     * @memberof AnnounceRequest
     */
    message: string;
}

/**
 * Check if a given object implements the AnnounceRequest interface.
 */
export function instanceOfAnnounceRequest(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function AnnounceRequestFromJSON(json: any): AnnounceRequest {
    return AnnounceRequestFromJSONTyped(json, false);
}

export function AnnounceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnounceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AnnounceRequestToJSON(value?: AnnounceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

