/* tslint:disable */
/* eslint-disable */
/**
 * PalWorld OpenAPI
 * PalWorld OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KickRequest
 */
export interface KickRequest {
    /**
     * 
     * @type {string}
     * @memberof KickRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof KickRequest
     */
    message?: string;
}

/**
 * Check if a given object implements the KickRequest interface.
 */
export function instanceOfKickRequest(value: object): boolean {
    if (!('userId' in value)) return false;
    return true;
}

export function KickRequestFromJSON(json: any): KickRequest {
    return KickRequestFromJSONTyped(json, false);
}

export function KickRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KickRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function KickRequestToJSON(value?: KickRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'message': value['message'],
    };
}

