/* tslint:disable */
/* eslint-disable */
/**
 * PalWorld OpenAPI
 * PalWorld OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsResponse
 */
export interface MetricsResponse {
    /**
     * 
     * @type {number}
     * @memberof MetricsResponse
     */
    serverfps: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponse
     */
    currentplayernum: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponse
     */
    serverframetime: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponse
     */
    maxplayernum: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponse
     */
    uptime: number;
}

/**
 * Check if a given object implements the MetricsResponse interface.
 */
export function instanceOfMetricsResponse(value: object): boolean {
    if (!('serverfps' in value)) return false;
    if (!('currentplayernum' in value)) return false;
    if (!('serverframetime' in value)) return false;
    if (!('maxplayernum' in value)) return false;
    if (!('uptime' in value)) return false;
    return true;
}

export function MetricsResponseFromJSON(json: any): MetricsResponse {
    return MetricsResponseFromJSONTyped(json, false);
}

export function MetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serverfps': json['serverfps'],
        'currentplayernum': json['currentplayernum'],
        'serverframetime': json['serverframetime'],
        'maxplayernum': json['maxplayernum'],
        'uptime': json['uptime'],
    };
}

export function MetricsResponseToJSON(value?: MetricsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'serverfps': value['serverfps'],
        'currentplayernum': value['currentplayernum'],
        'serverframetime': value['serverframetime'],
        'maxplayernum': value['maxplayernum'],
        'uptime': value['uptime'],
    };
}

