/* tslint:disable */
/* eslint-disable */
/**
 * PalWorld OpenAPI
 * PalWorld OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsResponse
 */
export interface SettingsResponse {
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    difficulty: string;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    dayTimeSpeedRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    nightTimeSpeedRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    expRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palCaptureRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palSpawnNumRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palDamageRateAttack: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palDamageRateDefense: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    playerDamageRateAttack: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    playerDamageRateDefense: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    playerStomachDecreaceRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    playerStaminaDecreaceRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    playerAutoHPRegeneRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    playerAutoHpRegeneRateInSleep: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palStomachDecreaceRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palStaminaDecreaceRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palAutoHPRegeneRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palAutoHpRegeneRateInSleep: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    buildObjectDamageRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    buildObjectDeteriorationDamageRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    collectionDropRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    collectionObjectHpRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    collectionObjectRespawnSpeedRate: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    enemyDropItemRate: number;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    deathPenalty: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnablePlayerToPlayerDamage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableFriendlyFire: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableInvaderEnemy: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bActiveUNKO: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableAimAssistPad: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableAimAssistKeyboard: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    dropItemMaxNum: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    dropItemMaxNumUNKO: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    baseCampMaxNum: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    baseCampWorkerMaxNum: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    dropItemAliveMaxHours: number;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bAutoResetGuildNoOnlinePlayers: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    autoResetGuildTimeNoOnlinePlayers: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    guildPlayerMaxNum: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    palEggDefaultHatchingTime: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    workSpeedRate: number;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bIsMultiplay: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bIsPvP: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bCanPickupOtherGuildDeathPenaltyDrop: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableNonLoginPenalty: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableFastTravel: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bIsStartLocationSelectByMap: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bExistPlayerAfterLogout: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bEnableDefenseOtherGuildPlayer: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    coopPlayerMaxNum: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    serverPlayerMaxNum: number;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    serverName: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    serverDescription: string;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    publicPort: number;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    publicIP: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    rCONEnabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    rCONPort: number;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    region: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bUseAuth: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    banListURL: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    rESTAPIEnabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingsResponse
     */
    rESTAPIPort: number;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bShowPlayerList: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    allowConnectPlatform: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsResponse
     */
    bIsUseBackupSaveData: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingsResponse
     */
    logFormatType: string;
}

/**
 * Check if a given object implements the SettingsResponse interface.
 */
export function instanceOfSettingsResponse(value: object): boolean {
    if (!('difficulty' in value)) return false;
    if (!('dayTimeSpeedRate' in value)) return false;
    if (!('nightTimeSpeedRate' in value)) return false;
    if (!('expRate' in value)) return false;
    if (!('palCaptureRate' in value)) return false;
    if (!('palSpawnNumRate' in value)) return false;
    if (!('palDamageRateAttack' in value)) return false;
    if (!('palDamageRateDefense' in value)) return false;
    if (!('playerDamageRateAttack' in value)) return false;
    if (!('playerDamageRateDefense' in value)) return false;
    if (!('playerStomachDecreaceRate' in value)) return false;
    if (!('playerStaminaDecreaceRate' in value)) return false;
    if (!('playerAutoHPRegeneRate' in value)) return false;
    if (!('playerAutoHpRegeneRateInSleep' in value)) return false;
    if (!('palStomachDecreaceRate' in value)) return false;
    if (!('palStaminaDecreaceRate' in value)) return false;
    if (!('palAutoHPRegeneRate' in value)) return false;
    if (!('palAutoHpRegeneRateInSleep' in value)) return false;
    if (!('buildObjectDamageRate' in value)) return false;
    if (!('buildObjectDeteriorationDamageRate' in value)) return false;
    if (!('collectionDropRate' in value)) return false;
    if (!('collectionObjectHpRate' in value)) return false;
    if (!('collectionObjectRespawnSpeedRate' in value)) return false;
    if (!('enemyDropItemRate' in value)) return false;
    if (!('deathPenalty' in value)) return false;
    if (!('bEnablePlayerToPlayerDamage' in value)) return false;
    if (!('bEnableFriendlyFire' in value)) return false;
    if (!('bEnableInvaderEnemy' in value)) return false;
    if (!('bActiveUNKO' in value)) return false;
    if (!('bEnableAimAssistPad' in value)) return false;
    if (!('bEnableAimAssistKeyboard' in value)) return false;
    if (!('dropItemMaxNum' in value)) return false;
    if (!('dropItemMaxNumUNKO' in value)) return false;
    if (!('baseCampMaxNum' in value)) return false;
    if (!('baseCampWorkerMaxNum' in value)) return false;
    if (!('dropItemAliveMaxHours' in value)) return false;
    if (!('bAutoResetGuildNoOnlinePlayers' in value)) return false;
    if (!('autoResetGuildTimeNoOnlinePlayers' in value)) return false;
    if (!('guildPlayerMaxNum' in value)) return false;
    if (!('palEggDefaultHatchingTime' in value)) return false;
    if (!('workSpeedRate' in value)) return false;
    if (!('bIsMultiplay' in value)) return false;
    if (!('bIsPvP' in value)) return false;
    if (!('bCanPickupOtherGuildDeathPenaltyDrop' in value)) return false;
    if (!('bEnableNonLoginPenalty' in value)) return false;
    if (!('bEnableFastTravel' in value)) return false;
    if (!('bIsStartLocationSelectByMap' in value)) return false;
    if (!('bExistPlayerAfterLogout' in value)) return false;
    if (!('bEnableDefenseOtherGuildPlayer' in value)) return false;
    if (!('coopPlayerMaxNum' in value)) return false;
    if (!('serverPlayerMaxNum' in value)) return false;
    if (!('serverName' in value)) return false;
    if (!('serverDescription' in value)) return false;
    if (!('publicPort' in value)) return false;
    if (!('publicIP' in value)) return false;
    if (!('rCONEnabled' in value)) return false;
    if (!('rCONPort' in value)) return false;
    if (!('region' in value)) return false;
    if (!('bUseAuth' in value)) return false;
    if (!('banListURL' in value)) return false;
    if (!('rESTAPIEnabled' in value)) return false;
    if (!('rESTAPIPort' in value)) return false;
    if (!('bShowPlayerList' in value)) return false;
    if (!('allowConnectPlatform' in value)) return false;
    if (!('bIsUseBackupSaveData' in value)) return false;
    if (!('logFormatType' in value)) return false;
    return true;
}

export function SettingsResponseFromJSON(json: any): SettingsResponse {
    return SettingsResponseFromJSONTyped(json, false);
}

export function SettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'difficulty': json['Difficulty'],
        'dayTimeSpeedRate': json['DayTimeSpeedRate'],
        'nightTimeSpeedRate': json['NightTimeSpeedRate'],
        'expRate': json['ExpRate'],
        'palCaptureRate': json['PalCaptureRate'],
        'palSpawnNumRate': json['PalSpawnNumRate'],
        'palDamageRateAttack': json['PalDamageRateAttack'],
        'palDamageRateDefense': json['PalDamageRateDefense'],
        'playerDamageRateAttack': json['PlayerDamageRateAttack'],
        'playerDamageRateDefense': json['PlayerDamageRateDefense'],
        'playerStomachDecreaceRate': json['PlayerStomachDecreaceRate'],
        'playerStaminaDecreaceRate': json['PlayerStaminaDecreaceRate'],
        'playerAutoHPRegeneRate': json['PlayerAutoHPRegeneRate'],
        'playerAutoHpRegeneRateInSleep': json['PlayerAutoHpRegeneRateInSleep'],
        'palStomachDecreaceRate': json['PalStomachDecreaceRate'],
        'palStaminaDecreaceRate': json['PalStaminaDecreaceRate'],
        'palAutoHPRegeneRate': json['PalAutoHPRegeneRate'],
        'palAutoHpRegeneRateInSleep': json['PalAutoHpRegeneRateInSleep'],
        'buildObjectDamageRate': json['BuildObjectDamageRate'],
        'buildObjectDeteriorationDamageRate': json['BuildObjectDeteriorationDamageRate'],
        'collectionDropRate': json['CollectionDropRate'],
        'collectionObjectHpRate': json['CollectionObjectHpRate'],
        'collectionObjectRespawnSpeedRate': json['CollectionObjectRespawnSpeedRate'],
        'enemyDropItemRate': json['EnemyDropItemRate'],
        'deathPenalty': json['DeathPenalty'],
        'bEnablePlayerToPlayerDamage': json['bEnablePlayerToPlayerDamage'],
        'bEnableFriendlyFire': json['bEnableFriendlyFire'],
        'bEnableInvaderEnemy': json['bEnableInvaderEnemy'],
        'bActiveUNKO': json['bActiveUNKO'],
        'bEnableAimAssistPad': json['bEnableAimAssistPad'],
        'bEnableAimAssistKeyboard': json['bEnableAimAssistKeyboard'],
        'dropItemMaxNum': json['DropItemMaxNum'],
        'dropItemMaxNumUNKO': json['DropItemMaxNum_UNKO'],
        'baseCampMaxNum': json['BaseCampMaxNum'],
        'baseCampWorkerMaxNum': json['BaseCampWorkerMaxNum'],
        'dropItemAliveMaxHours': json['DropItemAliveMaxHours'],
        'bAutoResetGuildNoOnlinePlayers': json['bAutoResetGuildNoOnlinePlayers'],
        'autoResetGuildTimeNoOnlinePlayers': json['AutoResetGuildTimeNoOnlinePlayers'],
        'guildPlayerMaxNum': json['GuildPlayerMaxNum'],
        'palEggDefaultHatchingTime': json['PalEggDefaultHatchingTime'],
        'workSpeedRate': json['WorkSpeedRate'],
        'bIsMultiplay': json['bIsMultiplay'],
        'bIsPvP': json['bIsPvP'],
        'bCanPickupOtherGuildDeathPenaltyDrop': json['bCanPickupOtherGuildDeathPenaltyDrop'],
        'bEnableNonLoginPenalty': json['bEnableNonLoginPenalty'],
        'bEnableFastTravel': json['bEnableFastTravel'],
        'bIsStartLocationSelectByMap': json['bIsStartLocationSelectByMap'],
        'bExistPlayerAfterLogout': json['bExistPlayerAfterLogout'],
        'bEnableDefenseOtherGuildPlayer': json['bEnableDefenseOtherGuildPlayer'],
        'coopPlayerMaxNum': json['CoopPlayerMaxNum'],
        'serverPlayerMaxNum': json['ServerPlayerMaxNum'],
        'serverName': json['ServerName'],
        'serverDescription': json['ServerDescription'],
        'publicPort': json['PublicPort'],
        'publicIP': json['PublicIP'],
        'rCONEnabled': json['RCONEnabled'],
        'rCONPort': json['RCONPort'],
        'region': json['Region'],
        'bUseAuth': json['bUseAuth'],
        'banListURL': json['BanListURL'],
        'rESTAPIEnabled': json['RESTAPIEnabled'],
        'rESTAPIPort': json['RESTAPIPort'],
        'bShowPlayerList': json['bShowPlayerList'],
        'allowConnectPlatform': json['AllowConnectPlatform'],
        'bIsUseBackupSaveData': json['bIsUseBackupSaveData'],
        'logFormatType': json['LogFormatType'],
    };
}

export function SettingsResponseToJSON(value?: SettingsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Difficulty': value['difficulty'],
        'DayTimeSpeedRate': value['dayTimeSpeedRate'],
        'NightTimeSpeedRate': value['nightTimeSpeedRate'],
        'ExpRate': value['expRate'],
        'PalCaptureRate': value['palCaptureRate'],
        'PalSpawnNumRate': value['palSpawnNumRate'],
        'PalDamageRateAttack': value['palDamageRateAttack'],
        'PalDamageRateDefense': value['palDamageRateDefense'],
        'PlayerDamageRateAttack': value['playerDamageRateAttack'],
        'PlayerDamageRateDefense': value['playerDamageRateDefense'],
        'PlayerStomachDecreaceRate': value['playerStomachDecreaceRate'],
        'PlayerStaminaDecreaceRate': value['playerStaminaDecreaceRate'],
        'PlayerAutoHPRegeneRate': value['playerAutoHPRegeneRate'],
        'PlayerAutoHpRegeneRateInSleep': value['playerAutoHpRegeneRateInSleep'],
        'PalStomachDecreaceRate': value['palStomachDecreaceRate'],
        'PalStaminaDecreaceRate': value['palStaminaDecreaceRate'],
        'PalAutoHPRegeneRate': value['palAutoHPRegeneRate'],
        'PalAutoHpRegeneRateInSleep': value['palAutoHpRegeneRateInSleep'],
        'BuildObjectDamageRate': value['buildObjectDamageRate'],
        'BuildObjectDeteriorationDamageRate': value['buildObjectDeteriorationDamageRate'],
        'CollectionDropRate': value['collectionDropRate'],
        'CollectionObjectHpRate': value['collectionObjectHpRate'],
        'CollectionObjectRespawnSpeedRate': value['collectionObjectRespawnSpeedRate'],
        'EnemyDropItemRate': value['enemyDropItemRate'],
        'DeathPenalty': value['deathPenalty'],
        'bEnablePlayerToPlayerDamage': value['bEnablePlayerToPlayerDamage'],
        'bEnableFriendlyFire': value['bEnableFriendlyFire'],
        'bEnableInvaderEnemy': value['bEnableInvaderEnemy'],
        'bActiveUNKO': value['bActiveUNKO'],
        'bEnableAimAssistPad': value['bEnableAimAssistPad'],
        'bEnableAimAssistKeyboard': value['bEnableAimAssistKeyboard'],
        'DropItemMaxNum': value['dropItemMaxNum'],
        'DropItemMaxNum_UNKO': value['dropItemMaxNumUNKO'],
        'BaseCampMaxNum': value['baseCampMaxNum'],
        'BaseCampWorkerMaxNum': value['baseCampWorkerMaxNum'],
        'DropItemAliveMaxHours': value['dropItemAliveMaxHours'],
        'bAutoResetGuildNoOnlinePlayers': value['bAutoResetGuildNoOnlinePlayers'],
        'AutoResetGuildTimeNoOnlinePlayers': value['autoResetGuildTimeNoOnlinePlayers'],
        'GuildPlayerMaxNum': value['guildPlayerMaxNum'],
        'PalEggDefaultHatchingTime': value['palEggDefaultHatchingTime'],
        'WorkSpeedRate': value['workSpeedRate'],
        'bIsMultiplay': value['bIsMultiplay'],
        'bIsPvP': value['bIsPvP'],
        'bCanPickupOtherGuildDeathPenaltyDrop': value['bCanPickupOtherGuildDeathPenaltyDrop'],
        'bEnableNonLoginPenalty': value['bEnableNonLoginPenalty'],
        'bEnableFastTravel': value['bEnableFastTravel'],
        'bIsStartLocationSelectByMap': value['bIsStartLocationSelectByMap'],
        'bExistPlayerAfterLogout': value['bExistPlayerAfterLogout'],
        'bEnableDefenseOtherGuildPlayer': value['bEnableDefenseOtherGuildPlayer'],
        'CoopPlayerMaxNum': value['coopPlayerMaxNum'],
        'ServerPlayerMaxNum': value['serverPlayerMaxNum'],
        'ServerName': value['serverName'],
        'ServerDescription': value['serverDescription'],
        'PublicPort': value['publicPort'],
        'PublicIP': value['publicIP'],
        'RCONEnabled': value['rCONEnabled'],
        'RCONPort': value['rCONPort'],
        'Region': value['region'],
        'bUseAuth': value['bUseAuth'],
        'BanListURL': value['banListURL'],
        'RESTAPIEnabled': value['rESTAPIEnabled'],
        'RESTAPIPort': value['rESTAPIPort'],
        'bShowPlayerList': value['bShowPlayerList'],
        'AllowConnectPlatform': value['allowConnectPlatform'],
        'bIsUseBackupSaveData': value['bIsUseBackupSaveData'],
        'LogFormatType': value['logFormatType'],
    };
}

