/* tslint:disable */
/* eslint-disable */
/**
 * PalWorld OpenAPI
 * PalWorld OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShutdownRequest
 */
export interface ShutdownRequest {
    /**
     * 
     * @type {number}
     * @memberof ShutdownRequest
     */
    waittime: number;
    /**
     * 
     * @type {string}
     * @memberof ShutdownRequest
     */
    message?: string;
}

/**
 * Check if a given object implements the ShutdownRequest interface.
 */
export function instanceOfShutdownRequest(value: object): boolean {
    if (!('waittime' in value)) return false;
    return true;
}

export function ShutdownRequestFromJSON(json: any): ShutdownRequest {
    return ShutdownRequestFromJSONTyped(json, false);
}

export function ShutdownRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShutdownRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'waittime': json['waittime'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ShutdownRequestToJSON(value?: ShutdownRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'waittime': value['waittime'],
        'message': value['message'],
    };
}

